name: novandi
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  get_it: ^7.6.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  dio: ^5.3.3
  rxdart: ^0.27.7
  google_fonts: ^5.1.0
  intl: ^0.18.1
  dartz: ^0.10.1
  flutter_bloc: ^8.1.3
  flutter_styled_toast: ^2.2.1
  flutter_svg: ^2.0.9
  equatable: ^2.0.5
  shimmer: ^3.0.0
  easy_splash_screen: ^1.0.4
  email_validator: ^2.1.17
  uuid: ^4.2.1
  path_provider: ^2.0.15
  internet_connection_checker: ^1.0.0+1
  flutter_custom_clippers: ^2.1.0
  flutter_flavor: ^3.1.3
  file_picker: ^6.1.1
  image_cropper: ^5.0.1
  flutter_image_compress: ^2.1.0
  auth_buttons: ^3.0.2
  google_maps_flutter: ^2.5.1
  flutter_contacts: ^1.1.7+1
  contacts_service: ^0.6.3
  permission_handler: ^11.0.1
  media_picker_widget: ^1.0.6
#  firebase_core: ^2.24.2
#  firebase_auth: ^4.15.3
#  google_sign_in: ^6.2.1

  cupertino_icons: ^1.0.2

flutter_gen:
  line_length: 8000
  null_safety: true
  output: lib/core_module/gen

  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

dev_dependencies:
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.2
  flutter_lints: ^3.0.1
  hive_generator: ^2.0.1
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/png/
    - assets/svg/
